version: '3.8'

networks:
   dev:

services:
   nginx:
      image: nginx:stable-alpine
      ports:
         - '80:80'
         - '443:443'
      volumes:
         - './nginx.conf:/etc/nginx/nginx.conf'
         - '/etc/letsencrypt:/etc/letsencrypt'
      depends_on:
         - server
         - client
      networks:
         - dev

   server:
      build:
         context: ./server
      networks:
         - dev
      depends_on:
         - db

   client:
      build:
         context: ./client
      networks:
         - dev

   db:
      image: mysql:5.7
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: crud
      volumes:
         - db-data:/var/lib/mysql
      networks:
         - dev

volumes:
   db-data:
